server:
  port: 8090
spring:
  profiles:
    active: dev
    include: secret
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  servlet:
    multipart:
      max-file-size: 50MB # 파일 업로드 최대 크기
      max-request-size: ${spring.servlet.multipart.max-file-size}
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:mariadb://localhost:3306/db_dev # 마리아DB 접속 URL로 변경
    username: root # 마리아DB 사용자 이름으로 변경
    password: # 마리아DB 비밀번호로 변경
    driver-class-name: org.mariadb.jdbc.Driver # 마리아DB JDBC 드라이버로 변경
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: 7aceab051a1b9098200ba191293de531
            scope: profile_nickname, profile_image
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: '${custom.site.baseUrl}/{action}/oauth2/code/{registrationId}'
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  mvc:
    hiddenmethod:
      filter:
        enabled: true
mail:
  password: NEED_TO_INPUT
custom:
  security:
    oauth2:
      client:
        registration:
          kakao:
            devUser:
              oauthId: oauthId
              nickname: nickname

  rebate:
    rate: 0.7
  order:
    cancelableSeconds: 3600
  temp:
    dirPath: c:/temp/mb/temp
  genFile:
    dirPath: c:/temp/mb
  site:
    name: mb.oa.gg
    baseUrl: "http://localhost:${server.port}"
  tossPayments:
    widget:
      clientKey: test_ck_Gv6LjeKD8aj4lpdzwMz43wYxAdXy
      secretKey: secretKey
logging:
  level:
    com.ll.mb: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
